import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { ArrowLeft, Edit2, Plus, Image as ImageIcon, Video, Mic, Calendar, Repeat, } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
export function MomentViewer({ momentTitle, momentDescription, isRecurrent, records, babyName, onBack, onEdit, onAddNew, }) {
    const [selectedRecord, setSelectedRecord] = useState(records.length === 1 ? records[0].id : null);
    const currentRecord = records.find((r) => r.id === selectedRecord);
    const formatDate = (dateStr) => {
        const date = new Date(dateStr);
        return date.toLocaleDateString("pt-BR", {
            day: "2-digit",
            month: "long",
            year: "numeric",
        });
    };
    const getTimeAgo = (dateStr) => {
        const date = new Date(dateStr);
        const now = new Date();
        const diffTime = Math.abs(now.getTime() - date.getTime());
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
        if (diffDays === 0)
            return "Hoje";
        if (diffDays === 1)
            return "Ontem";
        if (diffDays < 7)
            return `${diffDays} dias atrás`;
        if (diffDays < 30)
            return `${Math.floor(diffDays / 7)} semanas atrás`;
        if (diffDays < 365)
            return `${Math.floor(diffDays / 30)} meses atrás`;
        return `${Math.floor(diffDays / 365)} anos atrás`;
    };
    return (_jsxs("div", { className: "min-h-screen bg-background pb-24", children: [_jsx("div", { className: "sticky top-0 z-10 bg-card/95 backdrop-blur-sm border-b border-border", children: _jsxs("div", { className: "max-w-4xl mx-auto px-4 py-4", children: [_jsxs("button", { onClick: onBack, className: "mb-3 -ml-2 h-9 px-2 py-1.5 text-sm font-medium hover:bg-muted rounded-lg flex items-center gap-2 text-foreground", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), "Voltar"] }), _jsx("div", { className: "flex items-start justify-between gap-3", children: _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1 flex-wrap", children: [_jsx("h1", { className: "text-xl sm:text-2xl md:text-3xl", children: momentTitle }), isRecurrent && (_jsxs("span", { className: "inline-flex items-center gap-1 px-2 py-1 text-xs bg-secondary text-secondary-foreground rounded-full", children: [_jsx(Repeat, { className: "w-3 h-3" }), "Recorrente"] }))] }), _jsx("p", { className: "text-xs sm:text-sm text-muted-foreground", children: momentDescription }), isRecurrent && (_jsxs("p", { className: "text-xs sm:text-sm text-accent mt-1", children: [records.length, " ", records.length === 1 ? "registro" : "registros"] }))] }) })] }) }), _jsx("div", { className: "max-w-4xl mx-auto px-4 py-6 sm:py-8", children: isRecurrent && records.length > 1 ? (
                /* Timeline View */
                _jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "space-y-3", children: records
                                .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                                .map((record, index) => (_jsx(motion.div, { initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, transition: { delay: index * 0.05 }, children: _jsx("button", { className: `w-full p-4 rounded-2xl border-2 transition-all duration-200 text-left ${selectedRecord === record.id
                                        ? "border-primary shadow-md bg-primary/5"
                                        : "border-border hover:border-primary/30"}`, onClick: () => setSelectedRecord(record.id), children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "flex-shrink-0 pt-1", children: _jsx("div", { className: `w-3 h-3 rounded-full ${selectedRecord === record.id
                                                        ? "bg-primary"
                                                        : "bg-muted-foreground/30"}` }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Calendar, { className: "w-4 h-4 text-muted-foreground" }), _jsx("span", { className: "text-sm", children: formatDate(record.date) })] }), _jsxs("p", { className: "text-xs text-muted-foreground", children: [getTimeAgo(record.date), " \u2022", " ", record.ageAtMoment || `${babyName} com X meses`] })] })] }) }) }, record.id))) }), _jsx(AnimatePresence, { mode: "wait", children: selectedRecord && currentRecord && (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -20 }, transition: { duration: 0.3 }, className: "rounded-2xl border border-border bg-card p-6", children: [_jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg mb-1", children: "Detalhes do Registro" }), _jsx("p", { className: "text-sm text-muted-foreground", children: formatDate(currentRecord.date) })] }), _jsxs("button", { onClick: () => onEdit(currentRecord.id), className: "px-3 py-1.5 text-sm rounded-xl border border-border hover:bg-muted flex items-center gap-2", children: [_jsx(Edit2, { className: "w-4 h-4" }), "Editar"] })] }), currentRecord.media.length > 0 && (_jsxs("div", { className: "mb-4", children: [_jsxs("h4", { className: "text-sm mb-3", children: ["M\u00EDdias (", currentRecord.media.length, ")"] }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 gap-3", children: currentRecord.media.map((media, idx) => (_jsxs("div", { className: "aspect-square rounded-xl bg-muted flex items-center justify-center overflow-hidden", children: [media.type === "photo" && (_jsx(ImageIcon, { className: "w-8 h-8 text-muted-foreground" })), media.type === "video" && (_jsx(Video, { className: "w-8 h-8 text-muted-foreground" })), media.type === "audio" && (_jsx(Mic, { className: "w-8 h-8 text-muted-foreground" }))] }, idx))) })] })), currentRecord.story && (_jsxs("div", { children: [_jsx("h4", { className: "text-sm mb-2", children: "Hist\u00F3ria" }), _jsx("p", { className: "text-sm text-muted-foreground leading-relaxed", children: currentRecord.story })] }))] }, selectedRecord)) })] })) : (
                /* Single Record View */
                _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, className: "rounded-2xl border border-border bg-card p-6", children: [_jsxs("div", { className: "flex items-start justify-between mb-6", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Calendar, { className: "w-5 h-5 text-primary" }), _jsx("span", { className: "text-base sm:text-lg", children: formatDate(records[0].date) })] }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [getTimeAgo(records[0].date), " \u2022", " ", records[0].ageAtMoment || `${babyName} com X meses`] })] }), _jsxs("button", { onClick: () => onEdit(records[0].id), className: "px-3 py-1.5 text-sm rounded-xl border border-border hover:bg-muted flex items-center gap-2", children: [_jsx(Edit2, { className: "w-4 h-4" }), "Editar"] })] }), records[0].media.length > 0 && (_jsxs("div", { className: "mb-6", children: [_jsx("h4", { className: "text-sm sm:text-base mb-3", children: "M\u00EDdias" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 gap-3", children: records[0].media.map((media, idx) => (_jsxs("div", { className: "aspect-square rounded-xl bg-muted flex items-center justify-center overflow-hidden", children: [media.type === "photo" && (_jsx(ImageIcon, { className: "w-8 h-8 sm:w-10 sm:h-10 text-muted-foreground" })), media.type === "video" && (_jsx(Video, { className: "w-8 h-8 sm:w-10 sm:h-10 text-muted-foreground" })), media.type === "audio" && (_jsx(Mic, { className: "w-8 h-8 sm:w-10 sm:h-10 text-muted-foreground" }))] }, idx))) })] })), records[0].story && (_jsxs("div", { children: [_jsx("h4", { className: "text-sm sm:text-base mb-3", children: "Hist\u00F3ria" }), _jsx("p", { className: "text-sm sm:text-base text-muted-foreground leading-relaxed", children: records[0].story })] }))] })) }), isRecurrent && (_jsx("div", { className: "fixed bottom-0 left-0 right-0 bg-card/95 backdrop-blur-sm border-t border-border shadow-lg", children: _jsxs("div", { className: "max-w-4xl mx-auto px-4 py-3 sm:py-4", children: [_jsxs("button", { onClick: onAddNew, className: "w-full h-12 sm:h-14 rounded-2xl bg-primary hover:bg-primary/90 transition-smooth text-white font-medium flex items-center justify-center gap-2", children: [_jsx(Plus, { className: "w-5 h-5" }), _jsx("span", { className: "text-sm sm:text-base", children: "Adicionar Novo Registro" })] }), _jsx("p", { className: "text-xs text-center text-muted-foreground mt-2", children: "Registre mais uma vez que este momento aconteceu" })] }) }))] }));
}
